In [7]:
import torch
torch.__version__

'2.9.1+cu126'

Introduction to tensors

In [9]:
## Creating tensors
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # used to check the dimensions of a tensor

0

In [11]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item() # item will take the number in the scalar tensor and turn it into a Python integetr

7

In [12]:
# Vector
vector = torch.tensor([7, 7]) # A vector is a single dimension tensor but can contain many numbers.
vector

tensor([7, 7])

In [13]:
# Check the number of dimensions of vector
vector.ndim

1

In [14]:
# Check shape of vector
vector.shape

torch.Size([2])

In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
# Check number of dimensions
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [25]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [37]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[7.7316e-01, 2.0876e-01, 5.9353e-01, 4.2838e-04],
         [4.4664e-01, 1.3434e-01, 9.7857e-02, 5.6574e-01],
         [3.7886e-02, 5.5456e-01, 6.5839e-01, 1.1246e-01]]),
 torch.float32)

In [38]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [39]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [40]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Creating a range and tensors like

In [ ]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future
zero_to_ten_deprecated

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\Douglas\AppData\Local\Temp\ipykernel_46916\1371721734.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [58]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [59]:
# Creating a tensor where dtype = torch.float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Getting information from tensors

In [60]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7666, 0.1110, 0.5385, 0.0494],
        [0.8254, 0.3284, 0.9822, 0.0314],
        [0.9122, 0.2867, 0.7330, 0.5520]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
