In [13]:
import torch
import random
torch.__version__

'2.9.1+cu126'

2. Create a random tensor with shape (7, 7).

In [15]:
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
         [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [16]:
random_tensor_2 = torch.rand(size=(1, 7))

random_tensor_2, random_tensor_2.dtype

product = torch.mm(random_tensor, random_tensor_2.mT)

product, product.shape

(tensor([[1.1061],
         [0.9868],
         [1.8999],
         [0.7716],
         [1.3174],
         [1.6353],
         [1.7395]]),
 torch.Size([7, 1]))

4. Set the random seed to 0 and do 2 & 3 over again.

In [20]:
RANDOM_SEED = 0
# Did 2 again
torch.manual_seed(0)
random_tensor = torch.rand(size=(7, 7))

# Did 3 again
#torch.manual_seed(seed=RANDOM_SEED)
random_tensor_2 = torch.rand(size=(1, 7))

torch.mm(random_tensor, random_tensor_2.mT)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [21]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [28]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
!nvidia-smi
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_one = torch.rand(size=(2, 3))
tensor_one_gpu = tensor_one.to(device)
#tensor_one_gpu

#torch.manual_seed(1234)
tensor_two = torch.rand(size=(2, 3))
tensor_two_gpu = tensor_two.to(device)
tensor_one_gpu, tensor_two_gpu



Tue Jan 13 02:20:39 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.74                 Driver Version: 591.74         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:64:00.0 Off |                  N/A |
| N/A   37C    P8              1W /   80W |     147MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))


In [32]:
# Shape of tensors
tens_gpu_1_shape = tensor_one_gpu.shape
print(f"tensor 1 shape = {tens_gpu_1_shape}")

tens_gpu_2_shape = tensor_two_gpu.shape
print(f"tensor 2 shape = {tens_gpu_2_shape}")

gpu_product = torch.mm(tensor_one_gpu, tensor_two_gpu.mT)
gpu_product, gpu_product.shape

tensor 1 shape = torch.Size([2, 3])
tensor 2 shape = torch.Size([2, 3])


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [34]:
# Find max
print(f"Maximum is {gpu_product.max()}")

# Find min
print(f"Minimum is {gpu_product.min()}")

Maximum is 0.5617256760597229
Minimum is 0.3647301495075226


In [36]:
# Actual answer

# Find max
max = torch.max(gpu_product)

# Find min
min = torch.min(gpu_product)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [40]:
# Find arg Max
max_idx = torch.argmax(gpu_product)

# Find arg Min
min_idx = torch.argmin(gpu_product)

max_idx, min_idx, gpu_product


(tensor(3, device='cuda:0'),
 tensor(0, device='cuda:0'),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])



In [43]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor_1 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_rand_tensor_1 = torch.squeeze(rand_tensor_1)
print(squeezed_rand_tensor_1.shape)

# Print out tensors and their shapes
print(f"First tensor: {rand_tensor_1}")
print(f"First tensor shape: {rand_tensor_1.shape}")

print(f"Second tensor: {squeezed_rand_tensor_1}")
print(f"Second tensor shape: {squeezed_rand_tensor_1.shape}")


torch.Size([10])
First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
First tensor shape: torch.Size([1, 1, 1, 10])
Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Second tensor shape: torch.Size([10])
